export const COURSE_CATEGORY_REQUEST = "COURSE_CATEGORY_REQUEST";
export const COURSE_CATEGORY_SUCCESS = "COURSE_CATEGORY_SUCCESS";
export const COURSE_CATEGORY_FAIL = "COURSE_CATEGORY_FAIL";

//----------------------get course catagory-----------------//

export const GET_CATAGORY_REQUEST = "GET_CATAGORY_REQUEST";
export const GET_CATAGORY_SUCCESS = "GET_CATAGORY_SUCCESS";
export const GET_CATAGORY_FAIL = "GET_CATAGORY_FAIL";

//------------------view course catagory------------//

export const VIEW_CATAGORY_REQUEST='VIEW_CATAGORY_REQUEST';
export const VIEW_CATAGORY_SUCCESS='VIEW_CATAGORY_SUCCESS';
export const VIEW_CATAGORY_FAIL='VIEW_CATAGORY_FAIL';

//--------------update catagory---------------//

export const UPDATE_CATAGORY_REQUEST='UPDATE_CATAGORY_REQUEST';
export const UPDATE_CATAGORY_SUCCESS='UPDATE_CATAGORY_SUCCESS';
export const UPDATE_CATAGORY_FAIL='UPDATE_CATAGORY_FAIL';

//------------delete catagory----------------//

export const DELETE_CATAGORY_REQUEST='DELETE_CATAGORY_REQUEST';
export const DELETE_CATAGORY_SUCCESSS='DELETE_CATAGORY_SUCCESSS';
export const DELETE_CATAGORY_FAIL='DELETE_CATAGORY_FAIL';